Repository vmware/purser, pull requests merged in 2018-12, with the labels that each got.

#118 Enhance cost computation in controller side
  pkg/controller/dgraph/dgraph.go
  pkg/controller/dgraph/models/query/cluster.go
  pkg/controller/dgraph/models/query/container.go
  pkg/controller/dgraph/models/query/daemonset.go
  pkg/controller/dgraph/models/query/deployment.go
  pkg/controller/dgraph/models/query/job.go
  pkg/controller/dgraph/models/query/namespace.go
  pkg/controller/dgraph/models/query/node.go
  pkg/controller/dgraph/models/query/pod.go
  pkg/controller/dgraph/models/query/pv.go
  pkg/controller/dgraph/models/query/pvc.go
  pkg/controller/dgraph/models/query/replicaset.go
  pkg/controller/dgraph/models/query/statefulset.go
  pkg/controller/dgraph/purge.go
  pkg/controller/utils/timeUtils.go
Labels: Controller, DB, cla-not-required, enhancement

#120 Update colors in UI for better visibility
  .gitignore
  pkg/controller/dgraph/models/pvc.go
  ui/src/app/modules/topo-graph/components/topo-graph.component.scss
  ui/src/app/modules/topo-graph/components/topo-graph.component.ts
Labels: cla-not-required

#122 Exclude demo gif from repo and update UI image tag
  README.md
  cluster/purser-ui-setup.yaml
  docs/img/purser-ui.gif
Labels: cla-not-required

#125 Add support for user preferences
  Dockerfile.in
  README.md
  cluster/purser-controller-setup.yaml
  cmd/controller/config/config.go
  cmd/controller/purserctrl.go
  pkg/controller/dgraph/dgraph.go
  pkg/utils/logutil.go
Labels: Controller, cla-not-required, enhancement

#126 Attempt 3 retries before failing subscriber notifications
  pkg/controller/dgraph/models/query/cluster.go
  pkg/controller/dgraph/models/query/container.go
  pkg/controller/dgraph/models/query/daemonset.go
  pkg/controller/dgraph/models/query/deployment.go
  pkg/controller/dgraph/models/query/job.go
  pkg/controller/dgraph/models/query/namespace.go
  pkg/controller/dgraph/models/query/node.go
  pkg/controller/dgraph/models/query/pod.go
  pkg/controller/dgraph/models/query/pv.go
  pkg/controller/dgraph/models/query/pvc.go
  pkg/controller/dgraph/models/query/replicaset.go
  pkg/controller/dgraph/models/query/statefulset.go
  pkg/controller/eventprocessor/notifier.go
Labels: cla-not-required

#127 Store labels of pods in dgraph
  pkg/controller/dgraph/models/label.go
  pkg/controller/dgraph/models/pod.go
  pkg/controller/eventprocessor/updater.go
Labels: Controller, DB, cla-not-required

#129 Add custom headers support for Subscriber
  README.md
  cluster/artifacts/example-subscriber.yaml
  pkg/apis/subscriber/v1/types.go
  pkg/controller/eventprocessor/notifier.go
  pkg/controller/payload.go
Labels: cla-not-required

#132 Changes for adding filters
  ui/src/app/modules/capacity-graph/components/capactiy-graph.component.html
  ui/src/app/modules/capacity-graph/components/capactiy-graph.component.scss
  ui/src/app/modules/capacity-graph/components/capactiy-graph.component.ts
  ui/src/app/modules/topo-graph/components/topo-graph.component.html
  ui/src/app/modules/topo-graph/components/topo-graph.component.scss
  ui/src/app/modules/topo-graph/components/topo-graph.component.ts
Labels: UI, enhancement

#136 Update developer guide with steps to run purser locally
  README.md
  docs/developers-guide.md
  docs/sourcecode-installation.md
Labels: cla-not-required, documetation

#130 Implement group update using enhance filtering of pods
  README.md
  cluster/artifacts/example-group.yaml
  cmd/controller/purserctrl.go
  docs/custom-group-installation-and-usage.md
  docs/plugin-usage.md
  pkg/apis/groups/v1/types.go
  pkg/controller/dgraph/dgraph.go
  pkg/controller/dgraph/models/group.go
  pkg/controller/dgraph/models/pod.go
  pkg/controller/dgraph/models/query/group.go
  pkg/controller/dgraph/models/query/label.go
  pkg/controller/dgraph/models/query/label_test.go
  pkg/controller/dgraph/models/query/pod.go
  pkg/controller/discovery/processor/cluster.go
  pkg/controller/eventprocessor/processor.go
  pkg/controller/eventprocessor/updater.go
  pkg/controller/payload.go
  pkg/controller/persistentVolume.go
  pkg/plugin/grouping.go
  pkg/plugin/utils.go
Labels: cla-not-required

#139 Add design doc for cloud pricing in purser
  docs/design/pricing.md
Labels: cla-not-required, documetation
