Repository vmware/purser, pull requests merged in 2019-02, with the labels that each got.

#153 Add Table view for logical groups in UI
  Makefile
  cmd/plugin/purser.go
  pkg/controller/controller.go
  pkg/controller/dgraph/dgraph.go
  pkg/controller/dgraph/models/container.go
  pkg/controller/dgraph/models/node.go
  pkg/controller/dgraph/models/process.go
  pkg/controller/dgraph/models/service.go
  ui/src/app/app.module.ts
  ui/src/app/app.routing.ts
  ui/src/app/modules/home/components/home.component.html
  ui/src/app/modules/home/home.module.ts
  ui/src/app/modules/logical-group/components/logical-group.component.css
  ui/src/app/modules/logical-group/components/logical-group.component.html
  ui/src/app/modules/logical-group/components/logical-group.component.spec.ts
  ui/src/app/modules/logical-group/components/logical-group.component.ts
  ui/src/app/modules/logical-group/logical-group.module.ts
  ui/src/app/modules/logical-group/services/logical-group.service.ts
  ui/src/json/logicalGroup.json
Labels: UI, cla-not-required

#157 UI improvements for Navigation
  ui/src/app/app.component.html
  ui/src/app/app.routing.ts
  ui/src/app/modules/capacity-graph/components/capactiy-graph.component.html
  ui/src/app/modules/capacity-graph/components/capactiy-graph.component.ts
  ui/src/app/modules/home/components/home.component.html
  ui/src/app/modules/logical-group/components/logical-group.component.html
  ui/src/app/modules/topo-graph/components/topo-graph.component.html
  ui/src/app/modules/topologyGraph/components/topologyGraph.component.html
  ui/src/assets/images/GitHub-Mark-32px.png
Labels: UI, cla-not-required

#159 Update deployment files
  README.md
  cluster/purser-controller-setup.yaml
  cluster/purser-database-setup.yaml
  cluster/purser-setup.yaml
  cluster/purser-ui-setup.yaml
  docs/sourcecode-installation.md
  ui/src/app/app.component.ts
  ui/src/app/modules/capacity-graph/services/capacity-graph.service.ts
  ui/src/app/modules/logical-group/services/logical-group.service.ts
  ui/src/app/modules/topo-graph/services/topo-graph.service.ts
  ui/src/app/modules/topologyGraph/services/topologyGraph.service.ts
Labels: cla-not-required, enhancement

#161 Fix number of live pods shown for custom groups
  pkg/controller/dgraph/models/query/group.go
  pkg/controller/eventprocessor/updater.go
Labels: Bug-Fix, UI, cla-not-required

#164 Bump up the value for the resource limits and requests for purser UI
  cluster/purser-setup.yaml
Labels: cla-not-required

#166 Fix rendering of network interactions
  cmd/controller/api/handlers.go
  ui/src/app/modules/topologyGraph/components/topologyGraph.component.html
Labels: Bug-Fix, UI, cla-not-required

#173 Populate aws rate card by default
  cmd/controller/purserctrl.go
  pkg/pricing/cloud.go
Labels: Pricing, cla-not-required, enhancement

#175 Populate price for unit resource
  cmd/controller/purserctrl.go
  pkg/controller/dgraph/models/rateCard.go
  pkg/pricing/aws/aws.go
  pkg/pricing/aws/convert.go
Labels: DB, Pricing, cla-not-required, enhancement

#177 Node instance costing
  cmd/controller/purserctrl.go
  pkg/controller/dgraph/models/constants.go
  pkg/controller/dgraph/models/node.go
  pkg/controller/dgraph/models/pod.go
  pkg/controller/dgraph/models/query/cluster.go
  pkg/controller/dgraph/models/query/container.go
  pkg/controller/dgraph/models/query/daemonset.go
  pkg/controller/dgraph/models/query/deployment.go
  pkg/controller/dgraph/models/query/group.go
  pkg/controller/dgraph/models/query/job.go
  pkg/controller/dgraph/models/query/namespace.go
  pkg/controller/dgraph/models/query/node.go
  pkg/controller/dgraph/models/query/pod.go
  pkg/controller/dgraph/models/query/pv.go
  pkg/controller/dgraph/models/query/pvc.go
  pkg/controller/dgraph/models/query/replicaset.go
  pkg/controller/dgraph/models/query/statefulset.go
  pkg/controller/dgraph/models/query/types.go
  pkg/controller/dgraph/models/rateCard.go
  pkg/controller/utils/k8sUtils.go
  pkg/pricing/aws/convert.go
  pkg/pricing/cloud.go
Labels: Controller, Pricing, cla-not-required, enhancement

#178 Handle custom group deletion
  pkg/controller/dgraph/models/group.go
  pkg/controller/eventprocessor/processor.go
  pkg/controller/eventprocessor/updater.go
Labels: cla-not-required

#179 Remove redundant code blocks and fix type of price
  pkg/controller/dgraph/models/constants.go
  pkg/controller/dgraph/models/node.go
  pkg/controller/dgraph/models/pod.go
  pkg/controller/dgraph/models/query/pod.go
  pkg/controller/dgraph/models/rateCard.go
  pkg/controller/eventprocessor/processor.go
  pkg/controller/eventprocessor/updater.go
  pkg/pricing/aws/convert.go
Labels: cla-not-required, refactor

#180 Include Purser logo in README.md
  README.md
Labels: cla-not-required

#182 Fix dgraph schema for float types
  pkg/controller/dgraph/dgraph.go
  pkg/controller/dgraph/models/container.go
Labels: Bug-Fix, DB, cla-not-required

#186 Display total cost and place holder for experimental feature
  ui/src/app/modules/capacity-graph/components/capactiy-graph.component.html
  ui/src/app/modules/topologyGraph/components/topologyGraph.component.html
Labels: UI, cla-not-required, enhancement

#187 Use nginx in UI container
  README.md
  cluster/purser-controller-setup.yaml
  cluster/purser-database-setup.yaml
  cluster/purser-ui-setup.yaml
  cmd/controller/api/routes.go
  docs/sourcecode-installation.md
  openapi.yaml
  ui/Dockerfile.deploy.purser
  ui/angular.json
  ui/e2e/src/app.e2e-spec.ts
  ui/nginx.conf
  ui/src/app/app.component.spec.ts
  ui/src/app/app.component.ts
Labels: cla-not-required, documetation, enhancement

#190 Update UI service port from 4200 to 80
  cluster/purser-ui-setup.yaml
Labels: Bug-Fix, cla-not-required
