Repository vmware/purser, pull requests merged in 2019-08, with the labels that each got.

#251 Disable login feature
  .make/Makefile.deploy.controller
  Dockerfile.in
  Makefile
  README.md
  cluster/purser-controller-setup.yaml
  cluster/purser-ui-setup.yaml
  cmd/controller/api/apiHandlers/authenticationHandlers.go
  ui/Dockerfile.deploy.purser
  ui/package.json
  ui/proxy.conf.json
  ui/src/app/app.component.ts
  ui/src/app/app.routing.ts
Labels: Bug-Fix, cla-not-required

#256 Fix in Developer Guide
  docs/developers-guide.md
Labels: bug, documetation

#201 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: cla-not-required
