Repository vmware/purser, pull requests merged in 2019-04, with the labels that each got.

#222 Update makefile to separate docker output files
  .gitignore
  .make/Makefile.deploy.controller
  Dockerfile.in
  Makefile
Labels: cla-not-required, enhancement

#223 Support 3 months cost history
  cmd/controller/api/api.go
  cmd/controller/api/apiHandlers/customGroupHandlers.go
  cmd/controller/api/apiHandlers/helpers.go
  cmd/controller/api/apiHandlers/hierarchyAndMetricAPIHandlers.go
  cmd/controller/api/routes.go
  cmd/controller/purserctrl.go
  pkg/apis/groups/v1/types.go
  pkg/controller/dgraph/models/group.go
  pkg/controller/dgraph/models/query/group.go
  pkg/controller/dgraph/models/query/helpers.go
  pkg/controller/dgraph/models/query/queries.go
  pkg/controller/dgraph/purge.go
  pkg/controller/eventprocessor/updater.go
  ui/src/app/app.component.html
  ui/src/app/app.module.ts
  ui/src/app/app.routing.ts
  ui/src/app/modules/logical-group/components/logical-group.component.html
  ui/src/app/modules/logical-group/components/logical-group.component.ts
  ui/src/app/modules/options/components/options.component.html
  ui/src/app/modules/options/components/options.component.scss
  ui/src/app/modules/options/components/options.component.spec.ts
  ui/src/app/modules/options/components/options.component.ts
  ui/src/app/modules/options/options.module.ts
Labels: cla-not-required, enhancement

#228 Show cost history in UI
  pkg/controller/dgraph/models/query/queries.go
  ui/src/app/modules/logical-group/components/logical-group.component.html
  ui/src/app/modules/logical-group/components/logical-group.component.ts
Labels: Bug-Fix, cla-not-required

#225 Add check for username for authentication.
  cmd/controller/api/apiHandlers/authenticationHandlers.go
  pkg/controller/dgraph/models/query/login.go
Labels: cla-not-required

#234 Fix for last month costs and login
  Makefile
  pkg/controller/dgraph/dgraph.go
  pkg/controller/dgraph/models/group.go
  pkg/controller/dgraph/models/query/login.go
  ui/src/app/modules/logical-group/components/logical-group.component.html
Labels: Bug-Fix, cla-not-required
